providerCode=Qwen
paramApplier=info.mengnan.dialogerai.rag.container.factory.QwenParamApplierModelFactory

CHAT=dev.langchain4j.community.model.dashscope.QwenChatModel
STREAMING_CHAT=dev.langchain4j.community.model.dashscope.QwenStreamingChatModel
EMBEDDING=dev.langchain4j.community.model.dashscope.QwenEmbeddingModel
IMAGE=dev.langchain4j.community.model.dashscope.WanxImageModel
