providerCode=OpenAI
paramApplier=info.mengnan.dialogerai.rag.container.factory.OpenAiParamApplierModelFactory

MODERATION=dev.langchain4j.model.openai.OpenAiModerationModel
IMAGE=dev.langchain4j.model.openai.OpenAiImageModel
