server:
  port: 7900

spring:
  application:
    name: dialoger-ai

  # 数据库配置
  datasource:
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 5
      maximum-pool-size: 20
      keepalive-time: 30000
    url: ${datasource.url:jdbc:mysql://127.0.0.1:3306/dialoger_ai?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${datasource.username:root}
    password: ${datasource.password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    banner: false

logging:
  level:
    info.mengnan.dialogerai.repository.mapper: OFF
    info.mengnan.dialogerai.server.config.info.mengnan.dialogerai.repository.config.SqlLogInterceptor: INFO
    org.springframework.web: INFO
    info.mengnan.dialogerai: INFO

# Elasticsearch配置
elasticsearch:
  host: ${elasticsearch.host:127.0.0.1}
  port: ${elasticsearch.port:9200}
  username: ${elasticsearch.username:}
  password: ${elasticsearch.password:}

# 文件存储路径
file:
  upload-dir: ./uploads

# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: jwt
  jwt-secret-key: ${jwt-secret-key:please-change-this-secret}
  is-log: false
  is-print: false
  is-read-cookie: false
  is-read-header: true
  token-prefix: Bearer
